name: BuildChecker
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # We need version 17 or higher for our app
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: 17
            distribution: 'temurin'
            cache: gradle
            
      # Validate gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      # Ensure gradlew is executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Prepare gradle for build
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Attempt to build
      - name: Run build with Gradle Wrapper
        run: ./gradlew
